version: 2.1

jobs:
  deploy-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "update apt"
          command: "sudo apt-get update"
      - run:
          name: "install python3-pip"
          command: "sudo apt-get install python3-pip"
      - run:
          name: "install deploy requirements"
          command: "pip3 install pexpect boto3"
      - add_ssh_keys:
          fingerprints:
            - "78:b0:41:3d:6b:5a:d6:82:2c:48:44:d5:a3:82:eb:a4"
      - run:
          name: "start deploy"
          command: "python3 deploy.py"

workflows:
  deploy-workflow:
    jobs:
      - deploy-prod
