# Generated by Django 3.2.8 on 2021-12-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211129_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
    ]
